### ISSUE TITLE
AOI Utilities - Add a New Layer

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis#81]
Got this error message when trying to clip from Landfire_EVT webservice on the server to the AOI. I'm running the addin on ArcMap 10.8.1. Gus has the same issue on 10.5.X.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'ESRI.ArcGIS.Catalog.IGxDataset'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{BDBBB3F4-D0B2-11D1-AED9-080009EC734B}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at BAGIS.frmAOIInfo.CmdAddLayer_Click(Object sender, EventArgs e) in C:\workspace\vb-bagis\src\AOI\frmAOIInfo.vb:line 983
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![image](https://user-images.githubusercontent.com/11510708/100944603-78c70a80-34b4-11eb-9cad-8a5c167de626.png)

![image](https://user-images.githubusercontent.com/11510708/100944245-b37c7300-34b3-11eb-8e0f-ea9c80f37481.png)

**Comment by lbross** [comment]
I think we agreed a couple of years ago to not make webservices available for importing to BAGIS due to concerns about possible projection mismatches if we leave this open to all webservices. Search for an e-mail called 'BAGIS Aoi Info - Add a new layer' from November 2018. Of course, we know that the webservices in our data bin will work fine. Here are a couple of suggestions for enabling this feature:
1. Check the webservice projection against the AOI projection when it is selected. If they don't match, warn the user of a potential error but allow them to continue if desired. This could be annoying if the projection doesn't match between our data bin and the AOI and the message pops every time. We would need to look into the projection info from the web service.
2. Check the webservice uri and only allow the user to continue if it is in the databin or (less restrictive) on our server

According to the old email, this is also an issue with the Settings form so, whatever our decision, we should be handling it the same in both places. Currently on the settings form, we catch that the input is a webservice and don't allow the user to continue. At the least, we should add this to the AOI Utilities form to avoid this exception.

It is technically possible to clip an image service using ArcMap because we are doing it in BAGIS-P. BTW that is a workaround for Gus if he needs this layer right away. The Data Manager in BAGIS-P has the capability to clip the evt file to the AOI.
